const MAX_PAGES_AMOUNT = 500;

const DEFAULT_GENRE_ID = 28;

const _API_ACCESS_TOKEN = "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJkOTU5YjY1YTczNmM0Y2UzYjg1MWU4ZWJkOTgzMTQ0NSIsInN1YiI6IjY2NmZlNmU4ZjE4MmU0MTlkYmQxZGNkOCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.bMQCcpMp6d0sr6as-D8C9bnCEaK26rOjkOjaLD1iqSE";

export {
    MAX_PAGES_AMOUNT,
    DEFAULT_GENRE_ID,
    _API_ACCESS_TOKEN
}