import type {Metadata} from "next";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import {Providers} from "@/app/providers";
import {app_main_font} from "@/fonts";
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body className={app_main_font.className}>
        <Providers>
            <Header/>
            <main>{children}</main>
            <Footer/>
        </Providers>
        </body>
        </html>
    );
}
